// <auto-generated />
using CheckinAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckinAPI.Migrations
{
    [DbContext(typeof(MarkContext))]
    [Migration("20240315191359_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CheckinAPI.Models.Mark", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("pic_url")
                        .HasColumnType("longtext");

                    b.Property<string>("qq")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("word_num")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("Mark");
                });

            modelBuilder.Entity("CheckinAPI.Models.Marklog", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pic_url")
                        .HasColumnType("longtext");

                    b.Property<string>("qq")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("word_num")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("Marklog");
                });

            modelBuilder.Entity("CheckinAPI.Models.Register", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("qq")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Register");
                });

            modelBuilder.Entity("CheckinAPI.Models.Remind", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("qq")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Remind");
                });
#pragma warning restore 612, 618
        }
    }
}
